version: "3.8"

services:
  genesis:
    container_name: genesis
    hostname: genesis
    image: "namada-genesis:${IMAGE_TAG:-latest}"
    environment:
    - VALIDATOR0_ADDR=30.0.0.12:27657
    - VALIDATOR1_ADDR=30.0.0.13:27657
    - VALIDATOR2_ADDR=30.0.0.14:27657
    volumes:
      - ./validator-0/:/validator-0
      - ./validator-1/:/validator-1
      - ./validator-2/:/validator-2
      - ./fullnode/:/fullnode
      - ./container_ready/:/container_ready
    networks:
      namada-net:
        ipv4_address: 30.0.0.11
  validator0:
    container_name: validator0
    hostname: validator0
    image: "namada:${IMAGE_TAG:-latest}"
    environment:
      - NAMADA_TOKIO_THREADS=4
      - NAMADA_RAYON_THREADS=4
      - NAMADA_LOG=info
      - NAMADA_LOG_FMT=json
      - TM_LOG_LEVEL=p2p:none,pex:error
      - CMT_LOG_LEVEL=p2p:none,pex:error
      - NAMADA_CMT_STDOUT=true
      - BASE_DIR=/validator-0
    volumes:
      - ./validator-0/:/validator-0
      - ./container_ready/:/container_ready
      - ./namada.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    networks:
      namada-net:
        ipv4_address: 30.0.0.12
  validator1:
    container_name: validator1
    hostname: validator1
    image: "namada:${IMAGE_TAG:-latest}"
    environment:
      - NAMADA_TOKIO_THREADS=4
      - NAMADA_RAYON_THREADS=4
      - NAMADA_LOG=info
      - NAMADA_LOG_FMT=json
      - TM_LOG_LEVEL=p2p:none,pex:error
      - CMT_LOG_LEVEL=p2p:none,pex:error
      - NAMADA_CMT_STDOUT=true
      - BASE_DIR=/validator-1
    volumes:
      - ./validator-1/:/validator-1
      - ./container_ready/:/container_ready
      - ./namada.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    networks:
      namada-net:
        ipv4_address: 30.0.0.13
  validator2:
    container_name: validator2
    hostname: validator2
    image: "namada:${IMAGE_TAG:-latest}"
    environment:
      - NAMADA_TOKIO_THREADS=4
      - NAMADA_RAYON_THREADS=4
      - NAMADA_LOG=info
      - NAMADA_LOG_FMT=json
      - TM_LOG_LEVEL=p2p:none,pex:error
      - CMT_LOG_LEVEL=p2p:none,pex:error
      - NAMADA_CMT_STDOUT=true
      - BASE_DIR=/validator-2
    volumes:
      - ./validator-2/:/validator-2
      - ./container_ready/:/container_ready
      - ./namada.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    networks:
      namada-net:
        ipv4_address: 30.0.0.14
  fullnode:
    container_name: fullnode
    hostname: fullnode
    image: "namada:${IMAGE_TAG:-latest}"
    environment:
      - NAMADA_TOKIO_THREADS=4
      - NAMADA_RAYON_THREADS=4
      - NAMADA_LOG=info
      - NAMADA_LOG_FMT=json
      - NAMADA_TM_STDOUT="true"
      - CMT_LOG_LEVEL=info
      - BASE_DIR=/fullnode
    volumes:
      - ./fullnode/:/fullnode
      - ./container_ready/:/container_ready
      - ./namada.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    networks:
      namada-net:
        ipv4_address: 30.0.0.15
  workload0:
    container_name: workload0
    hostname: workload0
    image: workload:latest
    restart: on-failure
    environment:
      - RPC=30.0.0.14:27658
      - FAUCET_SK=00dfd790bd727b708f8b846374c596d886eaf1ebf0fc4394530e0a9b24aa630963
      - MASP_INDEXER_URL=30.0.0.20:5000
    volumes:
      - ./container_ready/:/container_ready
      - ./workload.sh:/app/entrypoint.sh
    entrypoint: /app/entrypoint.sh
    networks:
      namada-net:
        ipv4_address: 30.0.0.16
  workload1:
    container_name: workload1
    hostname: workload1
    image: workload:latest
    restart: on-failure
    environment:
      - RPC=30.0.0.14:27658
      - FAUCET_SK=00dfd790bd727b708f8b846374c596d886eaf1ebf0fc4394530e0a9b24aa630963
      - MASP_INDEXER_URL=30.0.0.20:5000
    volumes:
      - ./container_ready/:/container_ready
      - ./workload.sh:/app/entrypoint.sh
    entrypoint: /app/entrypoint.sh
    networks:
      namada-net:
        ipv4_address: 30.0.0.17
  workload2:
    container_name: workload2
    hostname: workload2
    image: workload:latest
    restart: on-failure
    environment:
      - RPC=30.0.0.14:27658
      - FAUCET_SK=00dfd790bd727b708f8b846374c596d886eaf1ebf0fc4394530e0a9b24aa630963
      - MASP_INDEXER_URL=30.0.0.20:5000
    volumes:
      - ./container_ready/:/container_ready
      - ./workload.sh:/app/entrypoint.sh
    entrypoint: /app/entrypoint.sh
    networks:
      namada-net:
        ipv4_address: 30.0.0.18
  check:
    container_name: check
    hostname: check
    image: check:latest
    restart: on-failure
    environment:
      - RPC=30.0.0.14:27658
      - MASP_INDEXER_URL=30.0.0.20:5000
    volumes:
      - ./container_ready/:/container_ready
    networks:
      namada-net:
        ipv4_address: 30.0.0.19
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_DB: masp_indexer_local
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "masp_indexer_local"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 80s
    networks:
      namada-net:
        ipv4_address: 30.0.0.21
  masp-chain:
    container_name: masp-chain
    hostname: masp-chain
    image: masp-indexer-chain:${MASP_INDEXER_IMAGE_TAG:-latest}
    restart: on-failure
    environment:
      - COMETBFT_URL=http://30.0.0.12:27658
      - DATABASE_URL=postgres://postgres:password@postgres:5432/masp_indexer_local
    depends_on:
      postgres:
        condition: service_healthy
  masp-webserver:
    container_name: masp-webserver
    hostname: masp-webserver
    image: masp-indexer-webserver:${MASP_INDEXER_IMAGE_TAG:-latest}
    restart: on-failure
    environment:
      - PORT=5000
      - COMETBFT_URL=http://30.0.0.12:27658
      - DATABASE_URL=postgres://postgres:password@postgres:5432/masp_indexer_local
    networks:
      namada-net:
        ipv4_address: 30.0.0.20
  masp-block-filter:
    container_name: masp-block-filter
    hostname: masp-block-filter
    image: masp-indexer-block-filter:${MASP_INDEXER_IMAGE_TAG:-latest}
    restart: on-failure
    environment:
      - COMETBFT_URL=http://30.0.0.12:27658
      - DATABASE_URL=postgres://postgres:password@postgres:5432/masp_indexer_local
    depends_on:
      postgres:
        condition: service_healthy
networks:
  namada-net:
    driver: bridge
    ipam:
      config:
      - subnet: 30.0.0.0/24
