# Namada three validator devnet setup
# IMAGE_TAG=v0.33.0-inst podman-compose up
version: "3.8"

services:
  genesis:
    container_name: genesis
    hostname: genesis
    # image: namada-genesis:v0.33.0-inst
    image: "namada-genesis:${IMAGE_TAG:-latest}"
    environment:
    - VALIDATOR0_ADDR=30.0.0.12:27657
    - VALIDATOR1_ADDR=30.0.0.13:27657
    - VALIDATOR2_ADDR=30.0.0.14:27657
    volumes:
      - ./validator-0/:/validator-0
      - ./validator-1/:/validator-1
      - ./validator-2/:/validator-2
      - ./fullnode/:/fullnode
      - ./container_ready/:/container_ready
    networks:
      namada-net:
        ipv4_address: 30.0.0.11
  validator0:
    container_name: validator0
    hostname: validator0
    # image: namada:v0.33.0-inst
    image: "namada:${IMAGE_TAG:-latest}"
    environment:
      - NAMADA_TOKIO_THREADS=4
      - NAMADA_RAYON_THREADS=4
      - NAMADA_LOG=info
      - NAMADA_LOG_FMT=json
      - CMT_LOG_LEVEL=info
      - BASE_DIR=/validator-0
    volumes:
      - ./validator-0/:/validator-0
      - ./container_ready/:/container_ready
      - ./namada.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    networks:
      namada-net:
        ipv4_address: 30.0.0.12
  validator1: # validator
    container_name: validator1
    hostname: validator1
    # image: namada:v0.33.0-inst
    image: "namada:${IMAGE_TAG:-latest}"
    environment:
      - NAMADA_TOKIO_THREADS=4
      - NAMADA_RAYON_THREADS=4
      - NAMADA_LOG=info
      - NAMADA_LOG_FMT=json
      - CMT_LOG_LEVEL=info
      - BASE_DIR=/validator-1
    volumes:
      - ./validator-1/:/validator-1
      - ./container_ready/:/container_ready
      - ./namada.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    networks:
      namada-net:
        ipv4_address: 30.0.0.13
  validator2: # validator
    container_name: validator2
    hostname: validator2
    # image: namada:v0.33.0-inst
    image: "namada:${IMAGE_TAG:-latest}"
    environment:
      - NAMADA_TOKIO_THREADS=4
      - NAMADA_RAYON_THREADS=4
      - NAMADA_LOG=info
      - NAMADA_LOG_FMT=json
      - CMT_LOG_LEVEL=info
      - BASE_DIR=/validator-2
    volumes:
      - ./validator-2/:/validator-2
      - ./container_ready/:/container_ready
      - ./namada.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    networks:
      namada-net:
        ipv4_address: 30.0.0.14
  fullnode: # full node
    container_name: fullnode
    hostname: fullnode
    # image: namada:v0.33.0-inst
    image: "namada:${IMAGE_TAG:-latest}"
    environment:
      - NAMADA_TOKIO_THREADS=4
      - NAMADA_RAYON_THREADS=4
      - NAMADA_LOG=info
      - NAMADA_LOG_FMT=json
      - CMT_LOG_LEVEL=info
      - BASE_DIR=/fullnode
    volumes:
      - ./fullnode/:/fullnode
      - ./container_ready/:/container_ready
      - ./namada.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    networks:
      namada-net:
        ipv4_address: 30.0.0.15
  workload0:
    container_name: workload0
    hostname: workload0
    image: namada-scenario-tester:latest
    restart: on-failure
    environment:
      - VALIDATOR_RPC=30.0.0.12:27658
      - FAUCET_SK=00dfd790bd727b708f8b846374c596d886eaf1ebf0fc4394530e0a9b24aa630963
      - WORKERS=4
    volumes:
      - ./container_ready/:/container_ready
      - ./workload.sh:/app/entrypoint.sh
    entrypoint: /app/entrypoint.sh
    networks:
      namada-net:
        ipv4_address: 30.0.0.16
  workload1:
    container_name: workload1
    hostname: workload1
    image: namada-scenario-tester:latest
    restart: on-failure
    environment:
      - VALIDATOR_RPC=30.0.0.13:27658
      - FAUCET_SK=00dfd790bd727b708f8b846374c596d886eaf1ebf0fc4394530e0a9b24aa630963
      - WORKERS=4
    volumes:
      - ./container_ready/:/container_ready
      - ./workload.sh:/app/entrypoint.sh
    entrypoint: /app/entrypoint.sh
    networks:
      namada-net:
        ipv4_address: 30.0.0.17
  workload2:
    container_name: workload2
    hostname: workload2
    image: namada-scenario-tester:latest
    restart: on-failure
    environment:
      - TEST_STEPS=200
      - VALIDATOR_RPC=30.0.0.14:27658
      - FAUCET_SK=00dfd790bd727b708f8b846374c596d886eaf1ebf0fc4394530e0a9b24aa630963
      - WORKERS=4
    volumes:
      - ./container_ready/:/container_ready
      - ./workload.sh:/app/entrypoint.sh
    entrypoint: /app/entrypoint.sh
    networks:
      namada-net:
        ipv4_address: 30.0.0.18
  check:
    container_name: check
    hostname: check
    image: check:latest
    restart: on-failure
    environment:
      - RPC=http://30.0.0.15:27658
    volumes:
      - ./container_ready/:/container_ready
    networks:
      namada-net:
        ipv4_address: 30.0.0.19
networks:
  namada-net:
    driver: bridge
    ipam:
      config:
      - subnet: 30.0.0.0/24
