name: Rebuild namada images (triggerable)

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "The namada SHA commit to build"
        required: true
        type: string
      genesis_template_version:
        description: "The genesis template version"
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      registry_url: us-central1-docker.pkg.dev/molten-verve-216720/heliax-repository
    strategy:
      fail-fast: true
      matrix:
        images:
          - make: "build-config"
            image: "namada-config"
            tag: ""
          - make: "build-genesis"
            image: "namada-genesis"
            tag: ""
          - make: "build-namada"
            image: "namada"
            tag: ""
          - make: "build-namada-inst"
            image: "namada"
            tag: -inst

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to private registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.registry_url }}
          username: _json_key
          password: ${{ secrets.ANTITHESIS_GAR_JSON_KEY }}
      - name: Build & Push Image ${{ matrix.images.image }} with sha commit ${{ github.event.inputs.commit }}/${{ github.event.inputs.genesis_template_version }}
        run: |
          registry_url="${{ env.registry_url }}" sha=${{ github.event.inputs.commit }} genesis_template_version=${{ github.event.inputs.genesis_template_version }} make ${{ matrix.images.make }}
          docker push ${{ env.registry_url }}/${{ matrix.images.image }}:${{ github.event.inputs.commit }}${{ matrix.images.tag }}
  
  check-container:
    runs-on: ubuntu-latest
    env:
      registry_url: us-central1-docker.pkg.dev/molten-verve-216720/heliax-repository
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.registry_url }}
          username: _json_key
          password: ${{ secrets.ANTITHESIS_GAR_JSON_KEY }}
      - name: Build & Push Image Check Container
        run: |
          registry_url="${{ env.registry_url }}" make check-container
          docker push ${{ env.registry_url }}/check:latest
